# Generated by Django 4.0.5 on 2022-07-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0002_rename_fname_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logged_in',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
