# Generated by Django 4.0.5 on 2022-07-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0003_user_last_logged_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='first_name',
        ),
    ]
